name: Codestyle

on:
  - push
  - pull_request

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install black
        run: |
          pip install --upgrade pip
          pip install black
      - name: Check code formatting with black
        run: black -l 120 . --diff --check
