name: Tests

on:
  - push
  - pull_request

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage httpx

      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 5

      - name: Run unit tests with coverage
        env:
          SECRET_KEY: "SECRET_TEST_KEY"
        run: |
          chmod +x coverage.sh
          ./coverage.sh

      - name: Send coverage report to codeclimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          set -ex
          wget -O reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x reporter
          ./reporter after-build